name: "Authenticate to GCP Artifact Registry using workload identity"
description: "Authenticate to GCP Artifact Registry using workload identity"
inputs:
  workload-id-provider:
    description: "Workload identity provider"
    required: true
  service-account:
    description: "Service account to use"
    required: true
  docker-gcp-registries:
    description: "GCP Artifact registry to login into. Check https://cloud.google.com/artifact-registry/docs/docker/authentication"
    required: true
    default: us-west1-docker.pkg.dev,us-central1-docker.pkg.dev
  
runs:
  using: "composite"
  steps:
    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ inputs.workload-id-provider }}
        service_account: ${{ inputs.service-account }}
        access_token_lifetime: '20m'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure docker for gcloud auth'
      shell: bash
      run: 'gcloud auth configure-docker ${{ inputs.docker-gcp-registries }}'
