name: "Authenticate to GCP Artifact Registry using workload identity"
description: "Authenticate to GCP Artifact Registry using workload identity"
inputs:
  workload-id-provider:
    description: "Workload identity provider"
    required: true
  service-account:
    description: "Service account to use"
    required: true
  artifact-registry:
    description: "Artifact registry to push the image to"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ inputs.workload-id-provider }}
        service_account: ${{ inputs.service-account }}
        access_token_lifetime: '20m'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Split location and app names
      env:
        REGISTRY: ${{ inputs.artifact-registry }}
      shell: bash
      run: |
          echo "location=${REGISTRY%%/*}" >> $GITHUB_OUTPUT
          echo "app_name=${REGISTRY##*/}" >> $GITHUB_OUTPUT

    - name: 'Configure docker for gcloud auth'
      shell: bash
      run: 'gcloud auth configure-docker ${{ steps.split.outputs.location }}'
