---
name: 'Run Container Workflow'
on:
  workflow_call:
    inputs:
      gcp-project:
        required: true
        type: string
      artifact-registry:
        required: true
        type: string
      workload-id-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      app-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      env-vars:
        required: false
        type: string

jobs:
  cloudrun-workflow:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload-id-provider }}
          service_account: ${{ inputs.service-account }}
          access_token_lifetime: '20m'

      - id: deploy
        if: github.ref != 'refs/heads/main'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ inputs.gcp-project }}
          env_vars: ${{ inputs.env-vars }}
          service: ${{ inputs.app-name }}
          image: ${{ inputs.artifact-registry }}:${{ inputs.tag }}
