name: 'Run Container Workflow'
on: 
  workflow_call:
    inputs:
      workload-id-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      access-token-lifetime:
        description: "GCP token expiration timeout"
        required: false
        type: string
        default: "20m" 
      artifact-registry:
        required: true
        type: string
      tags:
        required: true
        type: string
      platforms:
        type: string
        default: "linux/amd64"
      context:
        required: true
        type: string
      file:
        required: false
        type: string
      build-args:
        required: false
        type: string
      provenance:
        type: boolean
        required: false
        default: true
      docker-gcp-registries:
        type: string
        description: "GCP Artifact registry to login into. Check https://cloud.google.com/artifact-registry/docs/docker/authentication"
        default: "us-west1-docker.pkg.dev,us-central1-docker.pkg.dev"
      runs_on:
        default: "['ubuntu-latest']"
        type: string
        description: "github runner tags"
      timeout-minutes:
        default: 30
        type: number
        description: "Workflow timeout"
      environment:
        default: ''
        description: "Deployment environment in github"
        type: string
      debug_enabled:
        default: false
        required: false
        type: boolean
        description: "run tmate for troubleshooting"
      pr-comment:
        default: true
        type: boolean        
      summary:
        default: true
        type: boolean
      trivy-enabled:
        default: true
        type: boolean
      trivy-skip-dirs:
        type: string

jobs:
  auth-build-push-scan-container:
    runs-on: ${{ fromJson(inputs.runs_on) }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash 
    environment:
      name: ${{ inputs.environment }}
      url: "${{ inputs.environment != '' && format('https://{0}:{1}', inputs.artifact-registry, inputs.tags) || '' }}"
    permissions:
      actions: read
      contents: write
      id-token: write
      security-events: write
      attestations: write
      pull-requests: write
    steps:
      - name: Harden Runner
        if: runner.environment == 'github-hosted'
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
#          policy: ${{ inputs.debug_enabled == true && 'docker-debug' || 'docker' }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: inputs.debug_enabled == true 
        with:
          detached: true
          limit-access-to-actor: true
    
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: celo-org/trivy-composite-action@chatgpt-v3.0.0
        id: fs-scan
        if: inputs.trivy-enabled == true
        with:
          scan-ref: ${{ inputs.context }}
          scan-type: fs
          pr-comment: ${{ inputs.pr-comment }}
          skip-dirs: ${{ inputs.trivy-skip-dirs }}

      - name: Split location and app names
        id: split
        env:
          REGISTRY: ${{ inputs.artifact-registry }}
        run: |
          location=${REGISTRY%%/*}
          app_name=${REGISTRY##*/}
          echo "location=$location" >> $GITHUB_OUTPUT
          echo "app_name=$app_name" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload-id-provider }}
          service_account: ${{ inputs.service-account }}
          access_token_lifetime: ${{ inputs.access-token-lifetime }}
          token_format: access_token 

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.artifact-registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build, push and scan the container
        id: build-push
        uses: celo-org/docker-build-composite-action@v1.0.0-chatgpt
        with:
          platforms: ${{ inputs.platforms }}
          registry: ${{ inputs.artifact-registry }}
          tags: ${{ inputs.tags }}
          context: ${{ inputs.context }}
          dockerfile: ${{ inputs.file }}
          build-args: ${{ inputs.build-args }}
          push: ${{ fromJSON(true) }}
          summary: ${{ inputs.summary }}
          pr-comment: ${{ inputs.pr-comment }} 
          trivy-skip-dirs: ${{ inputs.trivy-skip-dirs }}
          skip-setup-trivy: true
          trivy-enabled: ${{ inputs.trivy-enabled }}

      - name: Generate Summary
        id: summary
        run: |
          echo "Container Image Summary:"
          echo "- Registry: ${{ steps.split.outputs.location }}"
          echo "- Application Name: ${{ steps.split.outputs.app_name }}"
          echo "- Tags: ${{ inputs.tags }}"
          echo "- Platforms: ${{ inputs.platforms }}"
          echo "- FileSystem Scan Results: ${{ steps.fs-scan.outputs.text-report }} "
          echo "- Image Scan Results: ${{ steps.build-push.outputs.text-report }} "
          echo "::set-output name=summary::Container build and push completed successfully for ${{ steps.split.outputs.app_name }}."
