






---
name: 'Run Go Tests'
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.23"
      path:
        required: true
        type: string
        description: "working directory"
      runs_on:
        default: "['ubuntu-latest']"
        type: string
        description: "github runner tags"
      timeout-minutes:
        default: 30
        type: number
        description: "Workflow timeout"

jobs:
  go-tests:
    container:
      image: golang:${{ inputs.go-version }}
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write
    runs-on: ${{ fromJson(inputs.runs_on) }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    defaults:
      run:
        shell: bash 
        working-directory: ${{ inputs.path }}

    steps:
      - uses: actions/checkout@v3
         
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: ${{ env.GO_VERSION }}
#
      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off -v ./...
