---
name: 'NPM Publish Workflow'
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      registry-url:
        required: false
        type: string
        default: "https://registry.npmjs.org"
      package-dir:
        required: true
        type: string
#      akeyless-api-gateway:
#        required: true
#        type: string
#      akeyless-github-access-id:
#        required: true
#        type: string
#      akeyless-token-path:
#        required: true
#        type: string
    secrets:
      npm-token:
        required: true


jobs:
  Npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
#      - name: Akeyless Get Secrets
#        id: get_auth_token
#        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
#        with:
#          api-url: ${{ inputs.akeyless-api-gateway }}
#          access-id: ${{ inputs.akeyless-github-access-id }}
#          #static-secrets: '{"/path/to/static/secret":"NPM_TOKEN"}'
#          static-secrets: "{\"${{ inputs.akeyless-token-path }}\":\"NPM_TOKEN\"}"
#

      - name: 'Setup Node JS'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }} 
      - run: yarn install
      - run: yarn build
      - run: cd ${{ inputs.package-dir }} && npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

