---
name: 'NPM Publish Workflow'
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      registry-url:
        required: false
        type: string
        default: "https://registry.npmjs.org"
      package-dir:
        required: true
        type: string
      install-dir:
        required: true
        type: string
      package-access:
        required: false
        type: string
        default: restricted
      akeyless-api-gateway:
        required: true
        type: string
      akeyless-github-access-id:
        required: true
        type: string
      akeyless-token-path:
        required: true
        type: string
jobs:

  npm-publish:
    runs-on: ['self-hosted', 'shared-runner']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: Build and publish npm package
        uses: ./github/actions/npm-publish
        with:
          node-version: ${{ inputs.node-version }}
          package-dir: ${{ inputs.package-dir }}
          install-dir: ${{ inputs.install-dir }}
          package-access: ${{ inputs.package-access }}
          akeyless-api-gateway: ${{ inputs.akeyless-api-gateway }}
          akeyless-github-access-id: ${{ inputs.akeyless-github-access-id }}
          akeyless-token-path: ${{ inputs.akeyless-token-path }}
