---
name: 'Run Container Workflow'
on: 
  workflow_call:
    inputs:
      workload-id-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      artifact-registry:
        required: true
        type: string
      vuln-type:
        required: false
        type: string
        default: "os,library"
      severity:
        required: false
        type: string
        default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"

jobs:
  Container-workflow:
    runs-on: ubuntu-latest
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d'
        with:
          workload_identity_provider: ${{ inputs.workload-id-provider }}
          service_account: ${{ inputs.service-account }}
          access_token_lifetime: '20m'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb'

      - name: Split location name
        id: split
        env:
          REGISTRY: ${{ inputs.artifact-registry }}
        run: echo "location=${REGISTRY%%/*}" >> $GITHUB_OUTPUT

      - name: 'Configure docker for gcloud auth'
        run: 'gcloud auth configure-docker ${{ steps.split.outputs.location }}'

      - name: Run Trivy vulnerability scanner
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/trivy-action@master
        env:
          REGISTRY: ${{ inputs.artifact-registry }}
        with:
          image-ref: "${{ inputs.artifact-registry }}:${{ github.event.pull_request.head.sha }}"
          vuln-type: "${{ inputs.vuln-type }}"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          format: "sarif"
          output: "trivy-results.sarif"


      - name: Run Trivy vulnerability scanner
        if: ${{ github.event_name == 'push' }}
        uses: aquasecurity/trivy-action@master
        env:
          REGISTRY: ${{ inputs.artifact-registry }}

        with:
          image-ref: "${{ inputs.artifact-registry }}:${{ github.sha }}"
          vuln-type: "${{ inputs.vuln-type }}"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

